template_path: templates/security-groups.py

sceptre_user_data:
    VpcId: !stack_output vpc::VpcId
    SecurityGroupIngress:
      - IpProtocol: tcp
        CidrIp: 0.0.0.0/0
        FromPort: 80
        ToPort: 80
    GroupDescription: "ELBsg"
    Tags:
      -
        Key: "Name"
        Value: "ELBsg"
      -
        Key: "Environment"
        Value: {{environment_path.0}}
      -
        Key: "Project"
        Value: {{environment_config.project_code}}
